### PR TITLE
feature/modal

### PR DESCRIPTION
**Pull request by Craft4Coffee**
Created modal
screen shot 2018-12-28 at 3 36 51 pm
screen shot 2018-12-28 at 3 36 34 pm
screen shot 2018-12-28 at 3 36 26 pm
screen shot 2018-12-28 at 3 36 06 pm
screen shot 2018-12-28 at 3 35 55 pm

### CODE REVIEW

**Comment by anpato** [comment]
Lets change the Add recipe in this menu to manage recipes , the dashboard has an add recipe Button now.

**Comment by renojvarghese** [comment]
Oh yea. I forgot about that. @Craft4Coffee could you update that in the html and css? If you make changes and committing to the same feature/modal branch, this pull request will update with your latest changes

**Comment by jsrpy** [comment]
Should #11 remove their `Add Recipe` button as discussed?

**Comment by anpato** [comment]
@jsrpy The add button will be on the navigation bar. Only recipe management will be available through the user settings.

**Comment by renojvarghese** [comment]
LGTM. Merging this in

**Pull request merged**
