### PR TITLE
Local storage setup

### PR DESCRIPTION
**Pull request by jtcll**

### CODE REVIEW

**Comment by jsrpy** [comment]
@jtcll Urm could you specify how to test out this functionality? There dashboard page is not setup (plaintext) and what is the usage of localstorage in this PR?

**Comment by jtcll** [comment]
😊 Yes, I was thinking of putting a testing note.  

We're using local storage for the user id to identify our recipes.  For the moment, the value is printing to the console.  I confirmed that the correct user id was retrieved for the user signed on.  

Once we've developed the Add Recipe page to save our recipes to Firebase, we'll reconfirm that it's working.

**Comment by jsrpy** [comment]
It's a bit unclear to me where the userid is printed or stored in my console:

feature_authorization_dashboard

**Comment by jtcll** [comment]
Sorry about that.  I re-added the console log.  I may have added it for my testing and removed it for security purposes 🤔.

image

**Comment by jsrpy** [comment]
OK, right now I see the uid printing out and stored in localstorage upon successful login. 

But are we intending to implement persistent login in this PR? If not, merge this PR; else, we need to add the [auth persistence logics](https://firebase.google.com/docs/auth/web/auth-state-persistence)
```
firebase.auth().setPersistence(firebase.auth.Auth.Persistence.SESSION)
  .then(function() { ...
```
and the user shall be free from login again in the same session.

**Comment by anpato** [comment]
Tested, LGTM

**Pull request merged**
