### PR TITLE
React Router

### PR DESCRIPTION
**Pull request by renojvarghese**
Added a router to go between the following different pages in the application:
http://localhost:3000/
http://localhost:3000/create-account
http://localhost:3000/dashboard
http://localhost:3000/dashboard/settings

To test:
1) `git checkout master` not necessary, but I personally like to always head back to master branch
2) `git pull` for the latest changes
3) `git checkout feature/react-router`
4) There should a folder called "react-app-cll" Make sure you are in the folder with a file called package.json. That folder is where the react app is.
5) `npm install` to get all the dependencies
6) `npm start` to start local dev environment
7) Go to the different URLs and verify that it works
 
Screenshots of what you might see:
screen shot 2018-12-27 at 5 44 40 pm
screen shot 2018-12-27 at 5 45 29 pm
screen shot 2018-12-27 at 5 44 24 pm
screen shot 2018-12-27 at 5 45 44 pm

### CODE REVIEW

**Comment by jtcll** [comment]
I did receive a Missing Origin Validation error caused by the webpack-dev-server dependency on a version >=3.1.11.
image

**Comment by jtcll** [comment]
LGTM

**Comment by renojvarghese** [comment]
@jtcll Were you able to get it working?

**Comment by anpato** [comment]
@renojvarghese also getting an error, connection timed out.

**Comment by renojvarghese** [comment]
@anpato try
`npm install -g npm@latest` reinstall npm
`rm -rf node_modules` remove all your node modules
`npm install` reinstall you node modules.

That might work

**Comment by jtcll** [comment]
> @jtcll Were you able to get it working?

@renojvarghese , Yes, it works fine without upgrading the webpack-dev-server.  We could update that later in a new PR.

**Comment by anpato** [comment]
All is good, some kind of permissions issue on my network, server is working fine now. LGTM
screen shot 2019-01-05 at 2 17 19 pm

**Comment by renojvarghese** [comment]
Awesome! Merging this in.

**Pull request merged**
