### PR TITLE
Feature/react dashboard

### PR DESCRIPTION
**Pull request by anpato**
button functionality working and updated css to reflect new dashboard layout

### CODE REVIEW

**Comment by jtcll** [comment]
This LGTM.  

I had to install/update bootstrap and reactstrap libraries and there were a few warnings 'defined but not used'.
image

**Comment by renojvarghese** [comment]
Took a look. It works well @anpato . I echo what Jenny said. There are some components you imported that you did not use. Just remove the import statements for Card, CardImg etc. unless you need them in the component.
I got the following: 
./src/components/Dashboard/components/Card.js
  Line 3:   'Card' is defined but never used                                                                                                                                                                                                                                                                                                                                  no-unused-vars
  Line 3:   'CardImg' is defined but never used                                                                                                                                                                                                                                                                                                                               no-unused-vars
  Line 3:   'CardText' is defined but never used                                                                                                                                                                                                                                                                                                                              no-unused-vars
  Line 4:   'Button' is defined but never used                                                                                                                                                                                                                                                                                                                                no-unused-vars
  Line 10:  Redundant alt attribute. Screen-readers already announce `img` tags as an image. You don’t need to use the words `image`, `photo,` or `picture` (or any specified custom words) in the alt prop                                                                                                                                                                   jsx-a11y/img-redundant-alt
  Line 15:  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

./src/components/Dashboard/components/Menu.js
  Line 4:  'CreateAccount' is defined but never used  no-unused-vars

./src/components/App/App.js
  Line 5:  'fire' is defined but never used  no-unused-vars

**Comment by renojvarghese** [comment]
Also do the same merge w/ master we went over on Tues. Since the we updated master, we need to merge master again to get the new code.

**Comment by anpato** [comment]
@renoj got it.

**Comment by jsrpy** [comment]
LGTM.

Actually we don't need to use Reactstrap to use bootstrap. We can just add bootstrap classes to the classnames of each JSX element. But anyway, not sure if it is a problem or not to use partly reactstrap and partly normal JSX.

**Comment by renojvarghese** [comment]
@anpato were you able to update the PR? I can still see some conflicts.

**Comment by anpato** [comment]
@renojvarghese  I haven't gotten a chance, I'll try to get to it tonight. You just want me to git push master?

**Comment by renojvarghese** [comment]
@anpato you can push to this branch. Just make sure to resolve the conflicts first by doing `git merge master`, finding any conflicting code, and pushing it up here.

**Comment by anpato** [comment]
@renojvarghese  All good to go.

**Comment by renojvarghese** [comment]
nice @anpato

**Pull request merged**
