### PR TITLE
add login functionality

### PR DESCRIPTION
**Pull request by jsrpy**
Basic login with email & password functionality:

screen shot 2019-01-16 at 3 22 15 am

Please add testing accounts on [firebase](https://console.firebase.google.com/u/0/project/receipe-test/authentication/users) at the moment.

### CODE REVIEW

**Comment by renojvarghese** [comment]
It seems that you committed the env.js file. I almost did that myself. I think it might be something with .gitignore. Could you add env.js to .gitignore?

**Comment by jsrpy** [comment]
Okay just committed. But I wasn't able to delete that file on github, that button leads to a 404.

**Comment by renojvarghese** [comment]
LGTM I was able to login with a user name and password.

**Comment by anpato** [comment]
screen shot 2019-01-18 at 8 41 00 am
LGTM!

**Pull request merged**
