### PR TITLE
react boilerplate in progress

### PR DESCRIPTION
**Pull request by jsrpy**
Still figuring out how to pad the response object from firebase DB into a desired `array -> object` format.

Please try out the boilerplate at the moment: dummy objects provided at App.js's `state` with axios, firebase, reactstrap set up.

### CODE REVIEW

**Comment by jsrpy** [comment]
I think we have to eject `Reactstrap` from dependency.

**Comment by anpato** [comment]
If bootstrap is an issue, I can try to integrate the slide carousel in a different way.

**Comment by jsrpy** [comment]
@anpato Wait, you are using bootstrap?

**Comment by anpato** [comment]
Bootstrap is only for the image carousel and a couple of forms, but like I said we can go about it a different way if bootstrap is too difficult to implement.

**Comment by jsrpy** [comment]
Understood. Conversation brings to #11

**Pull request merged**
