### PR TITLE
Boilerplate

### PR DESCRIPTION
**Pull request by jsrpy**
~~I actually incidentally squash my last commit on my local ?????~~

~~_`Stay Away`_~~

~~**Don't Merge this PR. Ignore It**~~

### CODE REVIEW

**Comment by jsrpy** [comment]
OK I finally got the Axios working with Get, Add, Delete functions with firebase db.

This commit switches back to normal JSX input form and list items to implement those ideas.

Which means:

1. eject dependency `reactstrap`
2. eject dependency `bootstrap`

firebase_boilerplate

Test this with your own *firebase key*, which you can copy from Firebase -> Project Overview. Put it in the `src/util` directory with the following format:

```
const config = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: ""
};

export default config;
```

**Comment by renojvarghese** [comment]
Maybe add env to .gitignore. Other than that LGTM

**Comment by anpato** [comment]
LGTM

**Comment by renojvarghese** [comment]
@jtcll @Craft4Coffee Did you get a chance to try to get this working? Give it a shot today or tomorrow, and let us know if you need some help. I want to make sure we all have an `env` file and can connect to firebase. It should make life easier later on

**Comment by jtcll** [comment]
@renojvarghese Yes, I got it working.  LGTM

**Comment by Craft4Coffee** [comment]
LGTM

**Comment by renojvarghese** [comment]
Merge complete!

**Pull request merged**
