### PR TITLE
Feature/create account page

### PR DESCRIPTION
**Pull request by jtcll**

### CODE REVIEW

**Comment by anpato** [comment]
@jtcll any particular reason why the email forms autocomplete was turned off? Just curious, but other than that  **LGTM**

**Comment by jsrpy** [comment]
Tested, LGTM!

So, the landing page = signin page and the create account page = the create account page. And the react was moved from another branch right?

It seems to me that @jtcll has been doing well with React. Positive outlook.

**Comment by jsrpy** [comment]
Btw, @jtcll please change component name into semantic name. E.g. /LandingPage/index.js -> LandingPage.js, and so on, and always use Capitalise first letter, so as to maintain readability.

**Comment by jtcll** [comment]
> @jtcll any particular reason why the email forms autocomplete was turned off? Just curious, but other than that **LGTM**

🤔 We had it on, then I noticed Justin had it off, so I took it off.  We can put it back 👍.

**Comment by jtcll** [comment]
> Btw, @jtcll please change component name into semantic name. E.g. /LandingPage/index.js -> LandingPage.js, and so on, and always use Capitalise first letter, so as to maintain readability.

👍 I'll do that.

**Comment by renojvarghese** [comment]
@jsrpy I think I named it `LandingPage\index.js` It makes importing it easier while also keeping components in separate folders. If we keep the name the way it is, importing looks like `import LandingPage from "./components/LandingPage"` If it was LandingPage/LandingPage.js, importing would look like `import LandingPage from "./components/LandingPage/LandingPage.js"`

**Comment by jsrpy** [comment]
@renojvarghese ehh then later on we might have 15 `index.js` in a project :joy:

**Comment by renojvarghese** [comment]
@jsrpy They're in each of their own folders. It's the way I structured my files at work, and I did the same on this project. It's my style preference, but I should have asked the team which they would prefer. Let's talk about it at the next meeting, and we can have another PR to change the filenames.

**Pull request merged**
