### PR TITLE
Added Dashboard Page and associated CSS

### PR DESCRIPTION
**Pull request by anpato**
dashboard layout

### CODE REVIEW

**Comment by jtcll** [comment]
LGTM

**Comment by jsrpy** [comment]
@anpato Would you fix the wrong img paths for the cards? Or is that okay?

**Comment by jsrpy** [comment]
@anpato 
1. Bootstrap for carousel is not responsive properly on mobile. Please confirm this issue valid
screen shot 2019-01-04 at 12 51 48 am

2. All images under `/img` are too big. The `landing-page.png` is even 19MB. Please go ahead compress them.

3. The menubar is responsive, but it's the same display as in desktop version. Do we want to keep that? Or actually expand the menubar on the head-nav bar?

**Comment by anpato** [comment]
@jsrpy yes I saw this the other day, I'll add in the media queries later today, as for Img paths, they are just place holders for the time being to see box sizing.

**Comment by anpato** [comment]
Updated media queries @jsrpy verified it on my end, can you double check, also can you take a look at the jquery code for the menu.

**Comment by renojvarghese** [comment]
screen shot 2019-01-03 at 5 14 51 pm
Looks better on mobile. I am running into a problem with the carousel. It flashes all the images in the carousel first before transitioning into the next slide. It may have to do with css transitions
screen shot 2019-01-03 at 5 17 14 pm

**Comment by anpato** [comment]
Fixed the carousel bug, found out it was an issue with the images active class shrinking them, also had to change the nav bars active class to nav-active due to adding in CSS elements for the carousels active class.

**Comment by renojvarghese** [comment]
Awesome job. LGTM

**Comment by anpato** [comment]
Are we supposed to merge these branches or are you doing it @renojvarghese

**Comment by jsrpy** [comment]
> Are we supposed to merge these branches or are you doing it @renojvarghese

This shall be done after all reviewers approve the changes.

Could @jtcll help approve the latest commit?

**Comment by jtcll** [comment]
LGTM

**Comment by renojvarghese** [comment]
Sweet! Merging this in

**Pull request merged**
