### PR TITLE
Feature/landing page

### PR DESCRIPTION
**Pull request by jtcll**
Added the latest React library and fonts.

### CODE REVIEW

**Comment by jtcll** [comment]
This PR is ready to be merged.

image

- verifies email and password length > 5 characters, invalid email/password signon
- navigates to Dashboard screen from signon
- navigates to the Create screen from signon

Sorry some of the commits from VS Code are from my other account.  I'm still trying to correct it.

**Comment by jsrpy** [comment]
Is #27 a continuation of this PR? If yes, please close this.

**Comment by renojvarghese** [comment]
@jsrpy I think its separate from #27 This the landing page. #27 should be the create account page. Both components may be edited to make sure they link to each other, but other than that, the code should be separate.

**Comment by jsrpy** [comment]
@renojvarghese Are we sure? #27 contains the commit f2fe06d while f2fe06d is the end of this #24 PR. In other words, #27 contains all the things there are in #24, and has been merged into master as well (i.e. #24 is _already in_ master).

**Comment by renojvarghese** [comment]
Oh snickers! You right @jsrpy. We should close this out @jtcll What probably happened was when you started the create account page, you branched of this branch instead of branching off master. Since we merged the create account page that contains all of these changes, we won't need this PR. I checked the changes we pulled into master, and it LGTM. We should be good to close this.

**Comment by jtcll** [comment]
Yes, that's exactly what I did.  I didn't branch off master.  okay closing.

**Comment by jsrpy** [comment]
snickers = chocolate bars 😄

**Pull request closed without merging**
